### ISSUE TITLE
Question about Annotation

### ISSUE THREAD

**Issue by voldemortX** [SIAnalytics/BMTT2022_SIA_track#2]
I wonder if you guys encountered this issue when using the MOTSynth data:
The out-of-image-border human boxes are clipped at the borders.

If so, how did you find the full boxes for training?

**Comment by seominseok0429** [comment]
Thank you for your interest in our research.

The code corresponding to this issue is as follows.

https://github.com/SIAnalytics/BMTT2022_SIA_track/blob/main/yolox/data/data_augment.py#L142-L145

**Comment by voldemortX** [comment]
@seominseok0429 Thanks for the quick reply!
I see that code is similar to the original BYTE codes, it uses a relatively large border to tolerate full boxes. So I have one more question that is related to this. Your provided detector predicts full boxes when evaluating, which is normal and expected for MOT17 (e.g., you can have a box -100, -100, 200, 200). However, when I use the MOTSynth dataset, I found the labels are all clipped at the border, so my trained model also predicts clipped boxes (e.g., box -100, -100, 200, 200 will become 0, 0, 200, 200 both in label and my pred). Do you encounter a similar issue? I'm very confused and don't know how to address that, do you think my dataset was corrupted or there is a solution for this?

**Comment by seominseok0429** [comment]
Didn't you extract the labels through the official pipeline??

As a result of checking, our label file was not clipped.

We share our label files. (https://drive.google.com/file/d/1g_P8uOWbvm6tg6xF2vOCd2xiJWguk0aH/view?usp=sharing)

**Comment by voldemortX** [comment]
Thanks for the reply, maybe my team's label extraction had some issues back in March. I'll check that.
 
> We share our label files.

It would be great if you could share the `train.json`, it is a rather big file though.

**Comment by seominseok0429** [comment]
+ Sorry. I didn't understand well. Our **train.json file is also clipped.**

Perhaps it is because we did not use l1_loss and only used **IoU loss**.  The exact reason will be answered after analysis. (https://github.com/SIAnalytics/BMTT2022_SIA_track/blob/main/yolox/models/yolo_head.py#L126-L132)

And we share our prediction file. Given that negative values ​​exist, the issue does not appear to have occurred.

[MOT17-03-FRCNN.txt](https://github.com/SIAnalytics/BMTT2022_SIA_track/files/8829624/MOT17-03-FRCNN.txt)

**Comment by voldemortX** [comment]
> + Sorry. I didn't understand well. Our **train.json file is also clipped.**
> 
> Perhaps it is because we did not use l1_loss and only used **IoU loss**.  The exact reason will be answered after analysis. (https://github.com/SIAnalytics/BMTT2022_SIA_track/blob/main/yolox/models/yolo_head.py#L126-L132)
> 
> And we share our prediction file. Given that negative values ​​exist, the issue does not appear to have occurred.
> 
> [MOT17-03-FRCNN.txt](https://github.com/SIAnalytics/BMTT2022_SIA_track/files/8829624/MOT17-03-FRCNN.txt)
> 
> 
> 

Thanks for your thourough answers! Looking forward for your further investigations!

**Comment by voldemortX** [comment]
Currently my guess is this robustness comes from Mosaic, what do you think? @seominseok0429

**Comment by seominseok0429** [comment]
you're right. This is because of the effects of Mosaic augmentation and mixup augmentation. Also, model soup greatly improves domain generalization performance.

**Comment by voldemortX** [comment]
@seominseok0429 Well this seems to conclude this issue. Our fast re-training of your 58.1 HOTA detection model just finished, it also shows similar characteristics (normally predicting out-of-border boxes).

Thanks for your helps again!

**Comment by seominseok0429** [comment]
Thanks again for your interest in our research! Connections from Cityscapes will also be revealed soon.
