### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by voldemortX** [SIAnalytics/BMTT2022_SIA_track#3]
@seominseok0429 quick question, is `stage3_last_77.9.pth.tar` in [here](https://drive.google.com/drive/folders/1edc3XEYMQlVSWkuEiGYyBdUAKI5MYz2O) the one used for your 63 HOTA final submission?

I don't see descriptions for models other than the first one in the readme.

Btw, what should I do if I want to make a test set submission? Should I just change these to `test` and use only one set of the `FRCNN` results?

https://github.com/SIAnalytics/BMTT2022_SIA_track/blob/5cdbed0e93e4c0583b12791a98a0b636f7a9c63b/exps/example/mot/yolox_x_source_only.py#L19

https://github.com/SIAnalytics/BMTT2022_SIA_track/blob/5cdbed0e93e4c0583b12791a98a0b636f7a9c63b/exps/example/mot/yolox_x_source_only.py#L103

**Comment by seominseok0429** [comment]
Our final model is CBAM + mixedstlye. Using stage3_last_77.9.pth.tar will achieve HOTA 63.xxx. (Code will be uploaded 6.20)

We manually extracted only FRCNN from the test set and submitted it. (The automation code will also be uploaded 6.20.)

The readme will also be revised in detail.

**Comment by voldemortX** [comment]
@seominseok0429 Thanks! I'll wait for the release then. In the meantime, I just extracted the FRCNN results manually and got 62.6 HOTA on MOT17 test server, so maybe it is not 63.xxx?

**Comment by seominseok0429** [comment]
The performance gap in the MOT17 trainset is almost no different from the final model, so it was written as 63.xxx.

I'll change it to 62.xx.

The 63.2 model will also be uploaded soon!

We apologize for any inconvenience!

**Comment by voldemortX** [comment]
> The performance gap in the MOT17 trainset is almost no different from the final model, so it was written as 63.xxx.
> 
> I'll change it to 62.xx.
> 
> The 63.2 model will also be uploaded soon!
> 
> We apologize for any inconvenience!

Oh the comments are train HoTA. I misunderstood as test.  No problems then.  I just need to know I run the code correct. Thanks!

**Comment by voldemortX** [comment]
@seominseok0429 The workshop is now concluded (your team made a nice presentation! We'd like to meet you but regretfully we could not attend the meeting in person). Could you upload the final checkpoint when you are convenient or give me a date for it? Thanks in advance.

**Comment by seominseok0429** [comment]
@voldemortX  It is very difficult to unify the network with the addition of CBAM and Mixed Style with the existing repo. (Because we changed the architecture in stage3) Therefore, I will create a separate repo and share the repo with only stage3.

I'll create it tomorrow and share the link!

It is being delayed because there are currently no GPUs available to evaluate.

Thanks!

**Comment by seominseok0429** [comment]
@voldemortX I uploaded a 63.2 checkpoints file(https://drive.google.com/file/d/1yi-7M5dTsiUu8cHVNDhMzuY1qgFfNrjK/view?usp=sharing). Code will be available at (https://github.com/seominseok0429/BMTT-full-code_) !!

**Comment by voldemortX** [comment]
> @voldemortX I uploaded a 63.2 checkpoints file(https://drive.google.com/file/d/1yi-7M5dTsiUu8cHVNDhMzuY1qgFfNrjK/view?usp=sharing). Code will be available at (https://github.com/seominseok0429/BMTT-full-code_) !!

Thanks a lot!
