### ISSUE TITLE
The validation set of the detection model.

### ISSUE THREAD

**Issue by dada-thu** [SIAnalytics/BMTT2022_SIA_track#4]
Thank you for your awesome work! 
Now I would like to reproduce the **warm-up** model. We have trained the model on v100 with 8 GPUs, but on our own validation set, there is a 1.5map difference between it and the warm-up model you provided. For accuracy alignment, can you share with me the validation set you used for detection?

**Comment by seominseok0429** [comment]
We used MOT17 trainset for the validation set. Are you correct in using our code as is?

**Comment by dada-thu** [comment]
Can you provide the json of the validation set and the corresponding mAP? Thanks!

**Comment by seominseok0429** [comment]
Okay, here is the validation set JSON file.  currently, I have no evaluation GPUs. so I don't give corresponding mAP. sorry.

https://drive.google.com/file/d/18ZFck-zvqTUuQFDDQJF3grBWDOQnMycu/view?usp=sharing

**Comment by dada-thu** [comment]
Thanks a lot.
