### ISSUE TITLE
The requirement for the GPU device

### ISSUE THREAD

**Issue by wangyirui** [SIAnalytics/BMTT2022_SIA_track#5]
Thanks for sharing this excellent work!

In the instruction, you mentioned that to reproduce your warm-up model performance, we need "8 GPUs with no less than 40G memory". I am wondering does it mean each GPU must have a memory no less than 40G or the total number of GPU memory should be no less than 40G (saying 5G * 8 GPUs)?

Thank you!

**Comment by seominseok0429** [comment]
That is, one gpu requires 40 GB of memory. In our experience, the larger the batch size, the better the performance.
