### ISSUE TITLE
Batch size of training the warm-up model

### ISSUE THREAD

**Issue by wangyirui** [SIAnalytics/BMTT2022_SIA_track#6]
Thanks for uploading both the technical report and the code.

In your report, you mentioned that the warm-up model was trained using 8 A100 GPUs, with a mini-batch size of 4:
(1) Does this mean each GPU will have 4 inputs, thus, the total batch size on all GPUs would be 8 x 4 = 32?
(2) In the README.MD, your example command to reproduce the training of the warm-up model uses a batch size of 48 (i.e., -d 8 -b 48). 

I am wondering, which configuration did you use to achieve the best warm-up model?

Thank you!

**Comment by seominseok0429** [comment]
There was a calculation error in the technical report. We will correct this. Our batch size is 48 and 6 images per gpu.
